// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6AehEpdEGBe4rBzgjm5hCk7I8C-7HWNc',
    appId: '1:236116239051:web:b37e0800a67e0110e6b14e',
    messagingSenderId: '236116239051',
    projectId: 'mlsc-uninstagram',
    authDomain: 'mlsc-uninstagram.firebaseapp.com',
    storageBucket: 'mlsc-uninstagram.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2aIRtukaj9KhIGwZBvRLm9w7UURKohzo',
    appId: '1:236116239051:android:ba95677677ad5354e6b14e',
    messagingSenderId: '236116239051',
    projectId: 'mlsc-uninstagram',
    storageBucket: 'mlsc-uninstagram.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbF8y-ZC8TL891ivnhYiAlVS6GopKypg4',
    appId: '1:236116239051:ios:feea2c4f5fde2b89e6b14e',
    messagingSenderId: '236116239051',
    projectId: 'mlsc-uninstagram',
    storageBucket: 'mlsc-uninstagram.firebasestorage.app',
    iosBundleId: 'com.example.mlscUninstagramProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbF8y-ZC8TL891ivnhYiAlVS6GopKypg4',
    appId: '1:236116239051:ios:feea2c4f5fde2b89e6b14e',
    messagingSenderId: '236116239051',
    projectId: 'mlsc-uninstagram',
    storageBucket: 'mlsc-uninstagram.firebasestorage.app',
    iosBundleId: 'com.example.mlscUninstagramProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6AehEpdEGBe4rBzgjm5hCk7I8C-7HWNc',
    appId: '1:236116239051:web:ff12e8ea5f590e88e6b14e',
    messagingSenderId: '236116239051',
    projectId: 'mlsc-uninstagram',
    authDomain: 'mlsc-uninstagram.firebaseapp.com',
    storageBucket: 'mlsc-uninstagram.firebasestorage.app',
  );
}
